# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f97073effcfea8fc7c72c62558e0c227b6318a98399ffbbb50234e244ba28f67bac54430d8c1d069d0c11ba714cc4cc054ddda5c09ce47d10bc3e180599f7bd

test:
  secret_key_base: afecd8a23197049427d8e707b9a2d3a3f64355a0d2ce582cdf88e36eacd76ab74c8f214483cc9f30a556e87fb659d198d8c03ca04c819c46e800a37ce10b7595

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
